# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K10s < Formula
  desc "A modern terminal UI for Kubernetes"
  homepage "https://github.com/shvbsle/k10s"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shvbsle/k10s/releases/download/v0.1.1/k10s_0.1.1_darwin_amd64.tar.gz"
      sha256 "4cdc369147500a1e530de6747a55ef3d664aa65fd10cbd503f65fda5ce27ca57"

      def install
        bin.install "k10s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shvbsle/k10s/releases/download/v0.1.1/k10s_0.1.1_darwin_arm64.tar.gz"
      sha256 "41f145fae04e520c8243ec99f49350d0da8f08808be83d5b9fa7033292fe01e1"

      def install
        bin.install "k10s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shvbsle/k10s/releases/download/v0.1.1/k10s_0.1.1_linux_amd64.tar.gz"
      sha256 "a689e819a7323a21f8f5022cce6b4580c9b8fec845bfaa2b4eb54b8461623582"
      def install
        bin.install "k10s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shvbsle/k10s/releases/download/v0.1.1/k10s_0.1.1_linux_arm64.tar.gz"
      sha256 "8473df9bd1202ff1e98e5725fab9fc4a33d9b3ef13a312a2ad301e71372c9269"
      def install
        bin.install "k10s"
      end
    end
  end

  test do
    system "#{bin}/k10s", "--version"
  end
end
